### ISSUE TITLE
Allow user to specify `max_batch_size`?

### ISSUE THREAD

**Issue by chaithyagr** [mrphys/tensorflow-nufft#28]
Currently the max_batch_size is heuristically calculated. While this is a great idea, I guess its also good to allow user to have freedom to also define this to have better control over the tradeoff of `Speed` vs `GPU memory`.
I can handle this PR if we agree its need, but not at the moment.

**Comment by chaithyagr** [comment]
This is a great idea but for now, I seem to have implemented the basic version which directly feeds from `nufft` `interp` and `spread` functions. I do agree that this makes codebase and also the module a bit clunky right now. But i had to do it for my personal project. I can start this PR for now as we work on the `Options` Module as you mentioned, what do you think?

**Comment by jmontalt** [comment]
Thank you for your contribution. However, I am not in favour of making "temporary" changes to the public API. I'll keep the PR open as it's a good starting point, but I don't think it is ready to be merged yet. I'll keep this in mind and will do my best to help with the implementation when I find some time. In the meantime, I would suggest that you keep this version for your own work while we set up the final solution.

**Comment by chaithyagr** [comment]
Ya, I was also not very happy with my own solution. But I dont have time yet to work on this. It is a nice-to-have feature though. For now, I have my own version.

**Comment by jmontalt** [comment]
This has been addressed in #30 and the requested feature will be available in the next release.

**Comment by chaithyagr** [comment]
Wonderful, thank you for your efforts @jmontalt !

**Comment by jmontalt** [comment]
No problem! It should be easy to add more options in the future. Anything else you would like to add, please do not hesitate to ask (or create a PR directly).
