### ISSUE TITLE
ImportError: cannot import name 'nufft_options_pb2'

### ISSUE THREAD

**Issue by guanghaoch** [mrphys/tensorflow-nufft#39]
Hi, I installed the package on Windows via

`pip install --force-reinstall --no-deps git+https://github.com/mrphys/tensorflow-nufft.git`

that creates the wheel locally. The installation was done without errors, but when I import the module it prompts errors.
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/48200532/221717780-4c548bde-6d60-43cf-bf21-b9744036e795.png">

Does anyone know what causes the problem?

**Comment by jmontalt** [comment]
Hi @guanghaoch , thank you for your message. The compilation of TensorFlow NUFFT is not so straightforward, and this installation workflow is not currently supported. Support for Windows is a work in progress and will be coming soon.

**Comment by jmontalt** [comment]
Hi @guanghaoch , thank you for your message. The compilation of TensorFlow NUFFT is not so straightforward, and this workflow is not currently supported. Support for Windows is a work in progress and will be coming soon.
