### ISSUE TITLE
how to specify number of modes/frequencies?

### ISSUE THREAD

**Issue by samaktbo** [mrphys/tensorflow-nufft#9]
Hi,

This isn't really an issue, I just have two clarification questions:

1. Its not clear to me how to specify the number of Fourier modes/frequences (that is, K in https://finufft.readthedocs.io/en/latest/math.html) in the current implementation. In the call signature for pfft.nufft, there doesn't seem to be an explicit argument for this.
2. It seems like the current implementation has switched type_1 and type_2 in comparison to https://finufft.readthedocs.io/en/latest/math.html, is this correct?

Thanks fo your help.

**Comment by jmontalt** [comment]
Hi @samaktbo,

1. The number of modes can be specified using the argument `grid_shape`. It maps exactly to the `nmodes` argument of FINUFFT.
2. No, the type-1 and type-2 transforms match those of FINUFFT, as well as the original naming from "Dutt A, Rokhlin V. Fast Fourier transforms for nonequispaced data. SIAM Journal on Scientific computing. 1993 Nov;14(6):1368-93". This is specified on [the docs](https://mrphys.github.io/tensorflow-nufft/_nufft_ops/tfft.nufft.html). Can I ask what confused you in this regard?

**Comment by samaktbo** [comment]
Oh! Thanks for the clarification, I ended up figuring out that probably the number of modes can be inferred form the grid shape. I think what was confusing me is that whenever I heard grid, I was thinking non-uniform points real-valued points, I only realized later that the integer lattice is also a grid. I think this is also partly why I thought the roles were switched. 

The main reason I thought there had been a switch is because the example that is given (the MRI example) is doing the opposite of what I wanted to do (@davidwhogg helped me see this): in my project the number of modes is always uniform, but the points of evaluation (pixels) are non-uniform but it seems like in that example, the pixels are sampled uniformly but the desire is to have non-uniform modes. Would you say that is accurate?

**Comment by jmontalt** [comment]
Indeed, that is correct. In MRI, we often measure spatial frequencies in a set of non-uniform points, and then we need to evaluate the NUDFT to obtain an image (on a grid of pixels, naturally).

It is useful to remember that the `transform_type` only indicates whether you're going from uniform to non-uniform (`'type_2'`) or non-uniform to uniform (`'type_1'`), but it says nothing about the direction of the transform in terms of signal/frequency domains. That is controlled independently by the `fft_direction` (use `'forward'` for signal -> frequency and `'backward'` for frequency -> signal).

When I have a chance I will try to add a couple more examples to help clarify this.
